name: Build Docker Image

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow on

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: |
        chmod +x ./build-docker-image.sh  # Make the script executable
        ./build-docker-image.sh
